# Generated by Django 5.1.3 on 2024-11-29 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_patientcard_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcard',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_cards', to='doctors.doctor'),
        ),
    ]
