# Generated by Django 5.1.3 on 2024-11-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
    ]
