# Generated by Django 5.1.3 on 2024-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20241129_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='work_schedule',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
