---
- name: Install chrome
  hosts: client_server
  become: yes
  vars_files: 
    - ../misc/vault.yml
  vars:
    ansible_become_pass: "{{ client_server_pass }}"

  tasks:
    - name: Ensure apt lists directory exists # Fails due lock if it doesn't exist
      file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages 
      apt: 
        upgrade: dist

    - name: Gnupg installation
      apt: 
        name: gnupg
        state: present

    - name: Add Google Chrome repository key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present

    - community.general.ufw:
        rule: allow
        port: ssh

    - name: Enable UFW
      community.general.ufw:
        state: enabled