---
- name: Install chrome
  hosts: client_server
  become: yes

  tasks:
    - name: Gnupg installation
      apt: 
        name: gnupg
        state: present

    - name: Add Google Chrome repository key
      apt_key:
        url: https://dl.google.com/linux/linux_signing_key.pub
        state: present

    - name: Add Google Chrome repository
      apt_repository:
        repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
        state: present

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present