---
- name: Install MySQL server and set up the database
  hosts: database_server
  become: yes
  vars_files: 
    - ../misc/vault.yml
  vars:
    ansible_become_pass: "{{ database_server_pass }}"
    sql_local_path: "../misc/db-data.sql"  # Path to the SQL file on the control node
    sql_remote_path: "/tmp/db-data.sql"

  tasks:
    - name: Ensure apt lists directory exists # Fails due lock if it doesn't exist
      file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages 
      apt: 
        upgrade: dist

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: true

    - name: Copy SQL file to the managed node
      copy:
        src: "{{ sql_local_path }}"
        dest: "{{ sql_remote_path }}"
        mode: '0644'

    - name: Load database schema and data from SQL file
      shell: |
        mysql -u root < {{ sql_remote_path }}
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Create MySQL user 
      mysql_user:
        name: webuser 
        password: "{{ db_web_pass }}" 
        priv: '*.*:ALL' 
        state: present

    - name: Allow access to port 80
      community.general.ufw:
        rule: allow
        port: '3306'

    - name: Clean up SQL file from the target system
      file:
        path: "{{ sql_remote_path }}"
        state: absent