---
- name: Configure database
  import_playbook: db.yml
  become: yes
  vars_files:
    - ../misc/vault.yml
  
- name: Configure client
  import_playbook: client.yml
  become: yes
  vars_files:
    - ../misc/vault.yml