---
- name: Configure database
  import_playbook: db.yml
  become: yes

- name: Configure website
  import_playbook: web.yml
  become: yes
  
- name: Configure client
  import_playbook: client.yml
  become: yes

- name: Add sample data to database
  import_playbook: db-sample-data.yml
  become: yes