---
- name: Setup webserver
  hosts: web_server
  become: yes
  vars_files: 
    - ../misc/vault.yml
  vars:
    ansible_become_pass: "{{ web_server_pass }}"

  tasks:
    - name: Ensure apt lists directory exists # Fails due lock if it doesn't exist
      file:
        path: /var/lib/apt/lists
        state: directory
        mode: '0755'

    - name: Update apt repository cache
      apt:
        update_cache: yes

    - name: Upgrade all packages 
      apt: 
        upgrade: dist

    - community.general.ufw:
        rule: allow
        port: ssh

    - name: Allow access to django port 8000
      community.general.ufw:
        rule: allow
        port: '8000'

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Install python-venv
      apt: 
        name: python3-venv
        state: present
    
    - name: Install setuptools 
      apt: 
        name: python3-setuptools 
        state: present

    - name: Copy website files
      copy:
        src: ../hospital/
        dest: /opt/hospital/
        owner: root
        group: root
        mode: '0755'

    - name: Template settings.py
      template:
        src: ../misc/settings.py.j2
        dest: /opt/hospital/hospital/settings.py
      vars:
        db_password: "{{ db_web_pass }}"
        db_ip: "{{ database_server_ip }}"

    - name: Build Docker image
      command: docker-compose -f /opt/hospital/docker-compose.yml up --build -d
